version: '3.1'

services:
  postbaber:
    image: postgres
    container_name: postbarber
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: gobarber

  mongobarber:
    image: mongo
    container_name: mongobarber
    ports:
      - 27017:27017

  redisbarber:
    image: redis:alpine
    container_name: redisbarber
    ports:
      - 6379:6379

